const BANCO_PREGUNTAS_FAMOSOS = {
  "A": [
    ["Tenista murciano, número 1 más joven en la historia del ranking ATP.", "Alcaraz"],
    ["Boxeador estadounidense, tricampeón mundial de los pesos pesados.", "Ali"],
    ["Piloto asturiano, campeón del mundo de Fórmula 1 en 2005 y 2006.", "Alonso"],
    ["Ciclista francés, primer hombre en ganar cinco Tours de Francia.", "Anquetil"],
    ["Tenista estadounidense, único hombre en lograr el Golden Slam.", "Agassi"],
    ["Ala-pívot griego, MVP de la NBA en 2019 y 2020.", "Antetokounmpo"],
    ["Pívot de la NBA, máximo anotador histórico hasta 2023.", "Abdul-Jabbar"],
    ["Cantante británica, Óscar a mejor canción original por 'Skyfall'.", "Adele"],
    ["Cantante estadounidense, Grammy a mejor artista revelación en 2000.", "Aguilera"],
    ["Cantante francés, apodado 'el Sinatra francés'.", "Aznavour"],
    ["Actor y guionista, Óscar al mejor guion original en 1998.", "Affleck"],
    ["Novelista chilena, autora de 'La casa de los espíritus'.", "Allende"],
    ["Escritor de ciencia ficción, autor de la saga 'Fundación'.", "Asimov"],
    ["Poeta italiano medieval, autor de 'La Divina Comedia'.", "Alighieri"],
    ["Novelista inglesa, autora de 'Orgullo y prejuicio'.", "Austen"],
    ["Actriz estadounidense, protagonista de 'Los vigilantes de la playa'.", "Anderson"],
    ["Naturalista británico, narrador de 'Planet Earth'.", "Attenborough"],
    ["Actriz estadounidense, protagonista de la serie 'Friends'.", "Aniston"],
    ["Película de Marvel de 2019, la más taquillera de la historia en su estreno.", "Avengers"],
    ["Película de Disney de 1992, Óscar a mejor canción original.", "Aladdin"],
    ["Película de 1984, ocho premios Óscar incluido mejor película.", "Amadeus"],
    ["Película francesa de 2001, cuatro premios César.", "Amélie"],
    ["Club neerlandés, tres Copas de Europa consecutivas (1971-1973).", "Ajax"],
    ["Club londinense, invicto en la Premier League 2003-04.", "Arsenal"],
    ["Club rojiblanco madrileño, campeón de Liga en 2013-14.", "Atlético"]
  ],
  "B": [
    ["Atleta jamaicano, récord mundial de los 100 metros lisos.", "Bolt"],
    ["Futbolista inglés, Champions League con el Manchester United en 1999.", "Beckham"],
    ["Tenista sueco, cinco Wimbledon consecutivos (1976-1980).", "Borg"],
    ["Portero italiano, récord de partidos en la Serie A.", "Buffon"],
    ["Alero de la NBA, tres MVP consecutivos con los Celtics (1984-1986).", "Bird"],
    ["Escolta de los Lakers, cinco anillos de la NBA.", "Bryant"],
    ["Equipo de Chicago, seis anillos de la NBA en los años noventa.", "Bulls"],
    ["Músico británico, creador del personaje Ziggy Stardust.", "Bowie"],
    ["Cantante estadounidense, récord de premios Grammy.", "Beyoncé"],
    ["Cantante canadiense de swing, cuatro premios Grammy.", "Bublé"],
    ["Cantante irlandés, líder de la banda U2.", "Bono"],
    ["Cantante escocesa, viral en 'Britain's Got Talent' en 2009.", "Boyle"],
    ["Actor español, primer Óscar de interpretación para España.", "Bardem"],
    ["Actor malagueño, nominado al Óscar por 'Dolor y gloria'.", "Banderas"],
    ["Apellido de las hermanas autoras de 'Jane Eyre' y 'Cumbres borrascosas'.", "Brontë"],
    ["Escritor argentino, autor de 'Ficciones' y 'El Aleph'.", "Borges"],
    ["Modelo brasileña, ex esposa de Tom Brady.", "Bündchen"],
    ["Película de 1959, once premios Óscar.", "Ben-Hur"],
    ["Película de 1995, Óscar a mejor película con Mel Gibson.", "Braveheart"],
    ["Superhéroe cuya película de 2008 dio un Óscar póstumo a Heath Ledger.", "Batman"],
    ["Serie sobre un profesor convertido en narcotraficante, 16 premios Emmy.", "Breaking Bad"],
    ["Club alemán, triplete de Liga, Copa y Champions en 2013.", "Bayern"],
    ["Club catalán, sextete de títulos en 2009.", "Barcelona"],
    ["Compositor alemán, estrenó su Novena Sinfonía ya sordo.", "Beethoven"],
    ["Banda británica, récord de números uno en la lista Billboard.", "Beatles"]
  ],
  "C": [
    ["Futbolista neerlandés, tres Balones de Oro en los años setenta.", "Cruyff"],
    ["Portero español, récord de partidos con la selección.", "Casillas"],
    ["Ciclista español, ganador de dos Tours de Francia.", "Contador"],
    ["Futbolista francés, ídolo del Manchester United en los noventa.", "Cantona"],
    ["Delantero uruguayo, máximo goleador histórico del PSG.", "Cavani"],
    ["Nombre de pila del futbolista portugués, cinco veces Balón de Oro.", "Cristiano"],
    ["Base de los Golden State Warriors, MVP de la NBA en 2015 y 2016.", "Curry"],
    ["Equipo de Cleveland, primer anillo de su historia en 2016.", "Cavaliers"],
    ["Cantante de Nirvana, icono del grunge.", "Cobain"],
    ["Rapero y productor, conocido como 'Diddy' o 'Puff Daddy'.", "Combs"],
    ["Actor estadounidense, Óscar por 'Syriana' (2006).", "Clooney"],
    ["Actor del cine mudo, Óscar honorífico en 1972.", "Chaplin"],
    ["Actor escocés, primer intérprete de James Bond en cine.", "Connery"],
    ["Actor estadounidense, protagonista de 'Misión Imposible'.", "Cruise"],
    ["Actor estadounidense, Óscar a mejor director por 'Bailando con lobos'.", "Costner"],
    ["Cantante estadounidense, protagonista infantil de 'Hannah Montana'.", "Cyrus"],
    ["Novelista español, autor de 'Don Quijote de la Mancha'.", "Cervantes"],
    ["Escritor francés, Nobel de Literatura en 1957.", "Camus"],
    ["Escritora británica, creadora del detective Poirot.", "Christie"],
    ["Rapera estadounidense, primera solista en ganar un Grammy a mejor álbum de rap.", "Cardi"],
    ["Musical llevado al cine, Óscar a mejor película en 2003.", "Chicago"],
    ["Película de 1942, Óscar a mejor película.", "Casablanca"],
    ["Club londinense, primera Champions League en 2012.", "Chelsea"],
    ["Club escocés, primer equipo británico en ganar la Copa de Europa.", "Celtic"],
    ["Director estadounidense, trilogía de 'El padrino'.", "Coppola"],
    ["Director de 'Titanic' y 'Avatar'.", "Cameron"]
  ],
  "D": [
    ["Cantautor estadounidense, Nobel de Literatura en 2016.", "Dylan"],
    ["Actor estadounidense, célebre por el capitán Jack Sparrow.", "Depp"],
    ["Actor estadounidense, Óscar en 2016 por 'El renacido'.", "DiCaprio"],
    ["Película de Tarantino, Óscar al mejor guion original en 2013.", "Django"],
    ["Club alemán, finalista de la Champions League en 2013.", "Dortmund"],
    ["Tenista serbio, récord histórico de Grand Slams masculinos.", "Djokovic"],
    ["Actriz británica, Óscar por 'Shakespeare in Love'.", "Dench"],
    ["Actor británico, tres Óscar a mejor actor protagonista.", "Day-Lewis"],
    ["Actor estadounidense, Óscar por 'Wall Street' (1988).", "Douglas"],
    ["Actor estadounidense, protagonista de 'Fast & Furious'.", "Diesel"],
    ["Cantante canadiense, autora de 'My Heart Will Go On'.", "Dion"],
    ["Delantero marfileño, máximo goleador histórico del Chelsea.", "Drogba"],
    ["Base esloveno, el más joven en lograr un triple-doble de 30 puntos en la NBA.", "Doncic"],
    ["Pívot de los Spurs, cinco anillos de la NBA.", "Duncan"],
    ["Equipo de Texas, campeón de la NBA en 2011.", "Dallas"],
    ["Tenor español, uno de los Tres Tenores.", "Domingo"],
    ["Nombre de pila de la cantante británica de 'Levitating', dos premios Grammy.", "Dua"],
    ["Actor estadounidense, nominado cuatro veces al Óscar.", "Dafoe"],
    ["Actor estadounidense, Óscar al mejor guion original en 1998.", "Damon"],
    ["Actriz y cantante alemana, icono de Hollywood de los años treinta.", "Dietrich"],
    ["Actor estadounidense, dos Óscar de interpretación.", "De Niro"],
    ["Actor francés, dos Césars a mejor actor.", "Depardieu"],
    ["Actor estadounidense, Óscar de reparto en 2024 por 'Oppenheimer'.", "Downey"],
    ["Presentadora de televisión estadounidense, Medalla de la Libertad en 2016.", "DeGeneres"],
    ["Novelista francés, autor de 'Los tres mosqueteros'.", "Dumas"],
    ["Novelista ruso, autor de 'Crimen y castigo'.", "Dostoievski"]
  ],
  "E": [
    ["Delantero camerunés, único en marcar en tres finales de Champions distintas con tres clubes diferentes.", "Eto'o"],
    ["Entrenador español, tres Europa League consecutivas al frente del Sevilla.", "Emery"],
    ["Nombre de pila del ciclista colombiano, campeón del Tour de Francia en 2019 con 22 años.", "Egan"],
    ["Tenista sueco, seis títulos de Grand Slam en los años ochenta.", "Edberg"],
    ["Alero apodado 'Dr. J', MVP tanto en la ABA como en la NBA.", "Erving"],
    ["Pívot camerunés, MVP de la NBA en 2023.", "Embiid"],
    ["Escolta de Minnesota, oro olímpico con Estados Unidos en 2024.", "Edwards"],
    ["Quarterback de los Broncos, dos anillos de Super Bowl.", "Elway"],
    ["Piloto de NASCAR, siete campeonatos, apodado 'The Intimidator'.", "Earnhardt"],
    ["Rapero de Detroit, más discos de rap vendidos en la historia de EE.UU.", "Eminem"],
    ["Nombre de pila del cantante británico autor de 'Rocket Man'.", "Elton"],
    ["Cantante irlandesa de música new age, varios premios Grammy.", "Enya"],
    ["Nombre de pila del cantante español, hijo de Julio Iglesias, autor de 'Bailando'.", "Enrique"],
    ["Actor y director, dos Óscar a mejor director en los años noventa y 2000.", "Eastwood"],
    ["Actor estadounidense, protagonista adolescente de 'High School Musical'.", "Efron"],
    ["Actor británico, Globo de Oro por la serie 'Luther'.", "Elba"],
    ["Escritor y semiólogo italiano, autor de 'El nombre de la rosa'.", "Eco"],
    ["Película de Spielberg de 1982, Óscar a los mejores efectos visuales.", "E.T."],
    ["Club inglés, campeón de la First Division en 1985 y 1987.", "Everton"],
    ["Cantante cubanoamericana, más de veinte discos de platino en su carrera.", "Estefan"]
  ],
  "F": [
    ["Tenista suizo, veinte títulos de Grand Slam en su carrera.", "Federer"],
    ["Piloto argentino, cinco campeonatos del mundo de F1 en los años cincuenta.", "Fangio"],
    ["Delantero colombiano, máximo goleador histórico de su selección junto a Radamel Falcao.", "Falcao"],
    ["Escudería de F1 con más títulos de constructores en la historia.", "Ferrari"],
    ["Base con cinco anillos de la NBA junto a los Lakers de Kobe Bryant.", "Fisher"],
    ["Actor y director, Óscar a mejor actor por 'Million Dollar Baby'.", "Freeman"],
    ["Actriz estadounidense, dos Óscar antes de cumplir los treinta años.", "Foster"],
    ["Actriz estadounidense, dos Óscar a mejor actriz en los años sesenta y setenta.", "Fonda"],
    ["Actor estadounidense, icónico por interpretar a Indiana Jones.", "Ford"],
    ["Novelista estadounidense, Nobel de Literatura en 1949.", "Faulkner"],
    ["Novelista estadounidense, autor de 'El gran Gatsby'.", "Fitzgerald"],
    ["Influencer italiana, pionera del marketing de moda en redes sociales.", "Ferragni"],
    ["Película de Disney de 2013, Óscar a mejor canción por 'Let It Go'.", "Frozen"],
    ["Serie estadounidense de los noventa ambientada en un café de Manhattan.", "Friends"],
    ["Selección campeona del Mundial de fútbol en 2018.", "Francia"],
    ["Cantante estadounidense, primera mujer incluida en el Salón de la Fama del Rock.", "Franklin"],
    ["Actor irlandés, nominado al Óscar por 'Doce años de esclavitud'.", "Fassbender"],
    ["Actor estadounidense, nominado al Óscar por interpretar a James Franco en '127 horas'.", "Franco"],
    ["Base de los Knicks en los años setenta, incluido en el Salón de la Fama del baloncesto.", "Frazier"],
    ["Cantante de Queen, considerado uno de los mejores vocalistas de la historia del rock.", "Freddie"]
  ],
  "G": [
    ["Primer español campeón de la NBA, dos anillos con los Lakers.", "Gasol"],
    ["Entrenador español, seis títulos de Champions League sumando etapas como jugador y técnico.", "Guardiola"],
    ["Delantero francés, campeón del Mundial en 2018.", "Griezmann"],
    ["Futbolista neerlandés, Balón de Oro en 1987.", "Gullit"],
    ["Tenista alemana, único Golden Slam femenino de la historia, en 1988.", "Graf"],
    ["Ala-pívot, MVP de la NBA en 2004, anillo con Boston en 2008.", "Garnett"],
    ["Pívot francés, tres veces Mejor Defensor del Año de la NBA.", "Gobert"],
    ["Cantante estadounidense, Óscar a mejor canción original por 'Shallow'.", "Gaga"],
    ["Cantautor francés, célebre por su vida bohemia y su relación con Jane Birkin.", "Gainsbourg"],
    ["Actor y director, Óscar a mejor director por 'Braveheart'.", "Gibson"],
    ["Actriz estadounidense, protagonista de 'El mago de Oz'.", "Garland"],
    ["Actor estadounidense, protagonista de 'Brokeback Mountain'.", "Gyllenhaal"],
    ["Novelista colombiano, Nobel de Literatura en 1982.", "García Márquez"],
    ["Escritor alemán, autor de 'Fausto'.", "Goethe"],
    ["Cantante y actriz estadounidense, exniña estrella de Disney convertida en artista global.", "Gomez"],
    ["Película de 2000, Óscar a mejor película con Russell Crowe.", "Gladiator"],
    ["Musical de 1978 protagonizado por John Travolta y Olivia Newton-John.", "Grease"],
    ["Club turco, ganador de la Copa de la UEFA en el año 2000.", "Galatasaray"],
    ["Cantante estadounidense, récord histórico de suscriptores en YouTube para una artista.", "Grande"],
    ["Creador de la serie animada 'Los Simpson'.", "Groening"]
  ],
  "H": [
    ["Piloto británico, siete campeonatos de F1, récord igualado con Schumacher.", "Hamilton"],
    ["Delantero francés, máximo goleador histórico del Arsenal.", "Henry"],
    ["Delantero belga, mejor jugador de la Premier League en la temporada 2014-15.", "Hazard"],
    ["Tenista suiza, número 1 más joven de la historia del ranking WTA.", "Hingis"],
    ["Base, MVP de la NBA en 2018 con los Houston Rockets.", "Harden"],
    ["Nombre de pila del pívot nigeriano, campeón de la NBA en 1994 y 1995.", "Hakeem"],
    ["Guitarrista estadounidense, considerado por la revista Rolling Stone el mejor de la historia.", "Hendrix"],
    ["Cantante estadounidense, récord de semanas en el número 1 con 'I Will Always Love You'.", "Houston"],
    ["Actor estadounidense, dos Óscar consecutivos en 1994 y 1995.", "Hanks"],
    ["Actor galés, Óscar a mejor actor por 'El silencio de los corderos'.", "Hopkins"],
    ["Actriz estadounidense, Óscar a mejor actriz de reparto por 'Los miserables'.", "Hathaway"],
    ["Novelista estadounidense, Nobel de Literatura en 1954.", "Hemingway"],
    ["Poeta griego al que se atribuyen 'La Ilíada' y 'La Odisea'.", "Homero"],
    ["Socialité estadounidense, pionera de los reality shows de telerrealidad en los 2000.", "Hilton"],
    ["Saga cinematográfica sobre un joven mago que estudia en Hogwarts.", "Harry Potter"],
    ["Actor estadounidense, dos Óscar de interpretación en los años setenta y ochenta.", "Hoffman"],
    ["Apellido de dos actrices, Audrey y Katharine, con múltiples Óscar entre ambas.", "Hepburn"],
    ["Ciclista de pista británico, seis medallas de oro olímpicas.", "Hoy"],
    ["Actriz y modelo británica, habitual de la prensa rosa en los años noventa.", "Hurley"],
    ["Piloto británico, campeón del mundo de F1 en 1976.", "Hunt"]
  ],
  "I": [
    ["Centrocampista español, autor del gol de la final del Mundial de 2010.", "Iniesta"],
    ["Delantero sueco, máximo goleador histórico de su selección nacional.", "Ibrahimović"],
    ["Ciclista navarro, cinco Tours de Francia consecutivos entre 1991 y 1995.", "Indurain"],
    ["Base, MVP de la NBA en el año 2001, apodado 'The Answer'.", "Iverson"],
    ["Base, campeón de la NBA en 2016 con los Cleveland Cavaliers.", "Irving"],
    ["Cantante español, el artista en español con más discos vendidos de la historia.", "Iglesias"],
    ["Actor británico, Óscar a mejor actor por 'Reversal of Fortune' (1990).", "Irons"],
    ["Dramaturgo noruego, autor de 'Casa de muñecas'.", "Ibsen"],
    ["Película de Christopher Nolan, Óscar a los mejores efectos visuales en 2011.", "Inception"],
    ["Club de Milán, ganador del triplete europeo en 2010.", "Inter"],
    ["Club argentino, récord de siete Copas Libertadores.", "Independiente"],
    ["Atleta rusa de salto con pértiga, récord mundial y dos oros olímpicos.", "Isinbayeva"],
    ["Cantante de rock británico, autor de 'White Wedding'.", "Idol"],
    ["Nombre de pila de una cantante y personaje mediático español conocida como 'la más grande'.", "Isabel"],
    ["Selección que logró el Grand Slam del Torneo de las Seis Naciones de rugby en 2023.", "Irlanda"],
    ["Tenista estadounidense, protagonista del partido más largo de la historia en Wimbledon 2010.", "Isner"]
  ],
  "J": [
    ["Alero, seis anillos de la NBA y seis veces MVP de las Finales.", "Jordan"],
    ["Base de los Lakers, cinco anillos de la NBA y tres veces MVP de la liga.", "Johnson"],
    ["Alero, máximo anotador histórico de la NBA con dos equipos distintos.", "James"],
    ["Pívot serbio, MVP de la NBA en 2021, 2022 y 2024.", "Jokic"],
    ["Delantero brasileño, único en marcar en todos los partidos de la fase final de un Mundial (1970).", "Jairzinho"],
    ["Cantante estadounidense, autor del álbum más vendido de la historia, 'Thriller'.", "Jackson"],
    ["Cantante británico, líder de los Rolling Stones.", "Jagger"],
    ["Rapero y empresario, el primero de su género en convertirse en multimillonario.", "Jay-Z"],
    ["Cantautor estadounidense, autor de 'Piano Man'.", "Joel"],
    ["Actriz estadounidense, Óscar de reparto por 'Girl, Interrupted'.", "Jolie"],
    ["Actriz estadounidense, la mejor pagada de Hollywood en 2018 y 2019.", "Johansson"],
    ["Actor australiano, protagonista de Wolverine durante casi dos décadas.", "Jackman"],
    ["Novelista irlandés, autor de 'Ulises'.", "Joyce"],
    ["Empresaria estadounidense, la multimillonaria hecha a sí misma más joven de la historia según Forbes.", "Jenner"],
    ["Película de 2019 sobre el origen de un icónico villano, Óscar a mejor actor.", "Joker"],
    ["Club italiano con más Scudettos en la historia de la Serie A.", "Juventus"],
    ["Cantante estadounidense de jazz, Grammy al álbum del año en 2003.", "Jones"],
    ["Jugador de béisbol, cinco anillos de la Serie Mundial con los Yankees.", "Jeter"],
    ["Nombre de pila de la actriz ganadora del Óscar por 'Erin Brockovich'.", "Julia"]
  ],
  "L": [
    ["Atleta estadounidense, nueve medallas de oro olímpicas.", "Lewis"],
    ["Nombre de pila del futbolista argentino, ocho veces Balón de Oro.", "Lionel"],
    ["Tenista australiano, único en ganar el Grand Slam de calendario en dos ocasiones.", "Laver"],
    ["Piloto austriaco, tres campeonatos de F1 y grave accidente en el Nürburgring de 1976.", "Lauda"],
    ["Nombre de pila del alero apodado 'King James', cuatro anillos de la NBA.", "LeBron"],
    ["Alero, MVP de las Finales de la NBA con dos equipos distintos.", "Leonard"],
    ["Cantante y actriz estadounidense, conocida como 'Jenny from the Block'.", "Lopez"],
    ["Músico británico, miembro de los Beatles y autor de 'Imagine'.", "Lennon"],
    ["Cantante estadounidense, uno de los pocos artistas en ganar un EGOT (Emmy, Grammy, Óscar y Tony).", "Legend"],
    ["Actriz estadounidense, la más joven en ganar el Óscar a mejor actriz en el siglo XXI.", "Lawrence"],
    ["Actor estadounidense, Óscar de reparto por 'Dallas Buyers Club'.", "Leto"],
    ["Poeta español, autor de 'Romancero gitano', fusilado en 1936.", "Lorca"],
    ["Novelista estadounidense, autor de 'La llamada de la selva'.", "London"],
    ["Actriz estadounidense, icono de la prensa rosa de los años 2000.", "Lohan"],
    ["Serie sobre un grupo de supervivientes en una isla, emitida entre 2004 y 2010.", "Lost"],
    ["Club inglés, Champions League de 2005 remontando un 0-3 en la final.", "Liverpool"],
    ["Equipo de la NBA con más anillos de la historia junto a los Celtics.", "Lakers"],
    ["Nombre de pila del trompetista de jazz, autor de 'What a Wonderful World'.", "Louis"],
    ["Rapera y actriz estadounidense, Globo de Oro por 'Chicago'.", "Latifah"],
    ["Actriz italiana, Óscar a mejor actriz en 1962.", "Loren"]
  ],
  "M": [
    ["Futbolista argentino, ocho Balones de Oro, el máximo de la historia.", "Messi"],
    ["Futbolista argentino, autor del 'Gol del Siglo' en el Mundial de 1986.", "Maradona"],
    ["Delantero francés, campeón del mundo en 2018 con 19 años.", "Mbappé"],
    ["Peleador irlandés de artes marciales mixtas, primero en poseer dos cinturones de la UFC a la vez.", "McGregor"],
    ["Centrocampista croata, Balón de Oro en 2018.", "Modrić"],
    ["Ciclista belga, considerado el mejor de la historia, cinco Tours de Francia.", "Merckx"],
    ["Ala-pívot, segundo máximo anotador histórico de la NBA.", "Malone"],
    ["Escolta, especialista en triples con récord de puntería en su época en la NBA.", "Miller"],
    ["Cantante estadounidense, conocida como 'la Reina del Pop'.", "Madonna"],
    ["Vocalista de Queen, fallecido en 1991.", "Mercury"],
    ["Cantante australiana, autora de 'Can't Get You Out of My Head'.", "Minogue"],
    ["Cantante estadounidense, protagonista de varias medias partes de la Super Bowl.", "Mars"],
    ["Actor estadounidense, Óscar por 'Dallas Buyers Club'.", "McConaughey"],
    ["Actriz estadounidense, Óscar por 'Siempre Alice'.", "Moore"],
    ["Actor irlandés, Óscar por 'Oppenheimer' en 2024.", "Murphy"],
    ["Poeta chilena, Nobel de Literatura en 1945.", "Mistral"],
    ["Rapera estadounidense, récord de entradas en las listas Billboard.", "Minaj"],
    ["Película de 1999, Óscar a los mejores efectos visuales.", "Matrix"],
    ["Club italiano, siete Copas de Europa en su historia.", "Milan"],
    ["Único club francés en ganar la Champions League, en 1993.", "Marsella"]
  ],
  "N": [
    ["Tenista español, récord de catorce títulos de Roland Garros.", "Nadal"],
    ["Delantero brasileño, fichaje más caro de la historia del fútbol.", "Neymar"],
    ["Tenista checoestadounidense, dieciocho títulos individuales de Grand Slam.", "Navratilova"],
    ["Ala-pívot alemán, MVP de la NBA en 2007 y campeón en 2011.", "Nowitzki"],
    ["Atleta finlandés, nueve medallas de oro olímpicas en los años veinte.", "Nurmi"],
    ["Rapero estadounidense, considerado uno de los mejores líricamente de la historia.", "Nas"],
    ["Cantante de Fleetwood Mac, doble integrante del Salón de la Fama del Rock.", "Nicks"],
    ["Actor estadounidense, tres Óscar de interpretación.", "Nicholson"],
    ["Actor estadounidense, Óscar por 'El color del dinero'.", "Newman"],
    ["Actor estadounidense, protagonista de 'El club de la lucha'.", "Norton"],
    ["Poeta chileno, Nobel de Literatura en 1971.", "Neruda"],
    ["Nombre de pila de la actriz australiana ganadora del Óscar por 'Las horas'.", "Nicole"],
    ["Saga cinematográfica basada en los libros de C.S. Lewis.", "Narnia"],
    ["Club italiano, campeón de la Serie A en 2023 tras 33 años de espera.", "Napoli"],
    ["Novelista ruso-estadounidense, autor de 'Lolita'.", "Nabokov"],
    ["Actor estadounidense de artes marciales, icono de los años ochenta y noventa.", "Norris"],
    ["Base canadiense, dos veces MVP consecutivo de la NBA en 2005 y 2006.", "Nash"]
  ],
  "O": [
    ["Atleta estadounidense, cuatro medallas de oro en los Juegos de Berlín 1936.", "Owens"],
    ["Jugador de hockey sobre hielo ruso, máximo goleador histórico de la NHL.", "Ovechkin"],
    ["Tenista japonesa, cuatro títulos de Grand Slam.", "Osaka"],
    ["Pívot, MVP de la NBA en el año 2000 y tres anillos consecutivos con los Lakers.", "O'Neal"],
    ["Cantante estadounidense, autor del álbum 'Blonde'.", "Ocean"],
    ["Vocalista de Black Sabbath, considerado padre del heavy metal.", "Osbourne"],
    ["Actor británico, Óscar por 'El instante más oscuro'.", "Oldman"],
    ["Novelista británico, autor de '1984' y 'Rebelión en la granja'.", "Orwell"],
    ["Poeta romano, autor de 'Las metamorfosis'.", "Ovidio"],
    ["Película de 2023 sobre el padre de la bomba atómica, siete premios Óscar.", "Oppenheimer"],
    ["Club portugués, campeón de la Champions League en 2004 con Mourinho como técnico.", "Oporto"],
    ["Nombre de pila de la cantante autora del álbum debut más escuchado en Spotify.", "Olivia"]
  ],
  "P": [
    ["Futbolista brasileño, tres veces campeón del mundo.", "Pelé"],
    ["Nadador estadounidense, deportista con más medallas olímpicas de la historia.", "Phelps"],
    ["Central español, campeón del mundo en 2010.", "Piqué"],
    ["Piloto francés, cuatro campeonatos mundiales de F1.", "Prost"],
    ["Base, máximo asistente histórico de la NBA.", "Paul"],
    ["Alero, seis anillos de la NBA con los Chicago Bulls.", "Pippen"],
    ["Cantante estadounidense, conocido como 'el Rey del Rock and Roll'.", "Presley"],
    ["Cantante estadounidense, cinco números uno consecutivos con un mismo álbum.", "Perry"],
    ["Cantante estadounidense, célebre por sus acrobacias aéreas en directo.", "Pink"],
    ["Actor estadounidense, Óscar de reparto por 'Once Upon a Time in Hollywood'.", "Pitt"],
    ["Actriz israelí-estadounidense, Óscar por 'Cisne negro'.", "Portman"],
    ["Actor estadounidense, Óscar por 'Esencia de mujer'.", "Pacino"],
    ["Actor estadounidense, Óscar por 'Joker'.", "Phoenix"],
    ["Escritor estadounidense, padre del relato de terror moderno.", "Poe"],
    ["Novelista francés, autor de 'En busca del tiempo perdido'.", "Proust"],
    ["Película surcoreana, Óscar a mejor película en 2020.", "Parásitos"],
    ["Selección campeona de la Eurocopa de 2016.", "Portugal"],
    ["Pintor español, autor del 'Guernica'.", "Picasso"],
    ["Actor británico, protagonista de la saga 'Crepúsculo'.", "Pattinson"]
  ],
  "Q": [
    ["Ciclista colombiano, subcampeón del Tour de Francia en 2013 y 2015.", "Quintana"],
    ["Banda británica cuya actuación en Live Aid de 1985 está considerada la mejor de la historia del rock.", "Queen"],
    ["Escritor español del Siglo de Oro, autor de 'El Buscón'.", "Quevedo"]
  ],
  "R": [
    ["Futbolista portugués, máximo goleador histórico del fútbol según la FIFA.", "Ronaldo"],
    ["Futbolista brasileño, Balón de Oro en 2005.", "Ronaldinho"],
    ["Delantero inglés, máximo goleador histórico de su selección.", "Rooney"],
    ["Remero británico, cinco medallas de oro en cinco Juegos Olímpicos consecutivos.", "Redgrave"],
    ["Pívot, MVP de la NBA en 1995.", "Robinson"],
    ["Ala-pívot, cinco anillos de la NBA, líder de rebotes de su época.", "Rodman"],
    ["Pívot, once anillos de la NBA, el récord absoluto en la historia de la liga.", "Russell"],
    ["Cantante de Barbados, fundadora de la marca de cosmética Fenty Beauty.", "Rihanna"],
    ["Productor musical, coautor de 'Uptown Funk'.", "Ronson"],
    ["Actor canadiense, protagonista de 'Matrix' y 'John Wick'.", "Reeves"],
    ["Actriz estadounidense, Óscar por 'Erin Brockovich'.", "Roberts"],
    ["Actor estadounidense, Óscar honorífico y fundador del festival de Sundance.", "Redford"],
    ["Novelista británica, autora de la saga de Harry Potter.", "Rowling"],
    ["Poeta francés, figura clave del simbolismo del siglo XIX.", "Rimbaud"],
    ["Película de 1976, Óscar a mejor película, sobre un boxeador de Filadelfia.", "Rocky"],
    ["Club argentino, uno de los más laureados de Sudamérica.", "River"],
    ["Actor británico, protagonista de la saga de Harry Potter en el cine.", "Radcliffe"],
    ["Central español, gol decisivo en el minuto 93 de la final de Champions de 2014.", "Ramos"]
  ],
  "S": [
    ["Tenista estadounidense, número 1 del mundo durante seis años consecutivos.", "Sampras"],
    ["Piloto brasileño de F1, tres campeonatos mundiales, fallecido en 1994.", "Senna"],
    ["Nombre de pila de la tenista estadounidense con 23 títulos de Grand Slam.", "Serena"],
    ["Entrenador argentino, al frente del Atlético de Madrid desde 2011.", "Simeone"],
    ["Piloto alemán de F1, siete campeonatos mundiales.", "Schumacher"],
    ["Delantero egipcio, máximo goleador africano en la historia de la Premier League.", "Salah"],
    ["Base, máximo asistente histórico de la NBA antes de la llegada de Chris Paul.", "Stockton"],
    ["Cantante estadounidense, apodado 'La Voz', autor de 'My Way'.", "Sinatra"],
    ["Cantante de rock estadounidense, apodado 'The Boss'.", "Springsteen"],
    ["Cantante estadounidense, artista con más premios Grammy al álbum del año.", "Swift"],
    ["Actriz estadounidense, récord de nominaciones al Óscar en la historia.", "Streep"],
    ["Actor estadounidense, creador y protagonista de la saga 'Rocky'.", "Stallone"],
    ["Actor estadounidense, Óscar por 'El método Williams'.", "Smith"],
    ["Director estadounidense, dos Óscar a mejor director.", "Spielberg"],
    ["Dramaturgo inglés, autor de 'Hamlet'.", "Shakespeare"],
    ["Novelista portugués, Nobel de Literatura en 1998.", "Saramago"],
    ["Cantante estadounidense, apodada 'la Princesa del Pop'.", "Spears"],
    ["Película de animación de 2001, ganadora del primer Óscar a mejor película animada.", "Shrek"],
    ["Serie de animación estadounidense, la más longeva de la historia de la televisión.", "Simpson"],
    ["Club andaluz, récord de siete títulos de Europa League.", "Sevilla"]
  ],
  "T": [
    ["Boxeador estadounidense, campeón más joven de la historia en los pesos pesados.", "Tyson"],
    ["Escolta, récord de triples anotados en un solo partido de la NBA.", "Thompson"],
    ["Cantante estadounidense, exmiembro de la boy band NSYNC.", "Timberlake"],
    ["Cantante estadounidense, apodada 'la Reina del Rock and Roll'.", "Turner"],
    ["Actriz sudafricana, Óscar por 'Monster'.", "Theron"],
    ["Actor estadounidense, protagonista de 'Grease' y 'Pulp Fiction'.", "Travolta"],
    ["Director estadounidense, dos Óscar al mejor guion original.", "Tarantino"],
    ["Novelista ruso, autor de 'Guerra y paz'.", "Tolstói"],
    ["Novelista estadounidense, autor de 'Las aventuras de Tom Sawyer'.", "Twain"],
    ["Película de 1997, once premios Óscar, empatando el récord histórico.", "Titanic"],
    ["Club inglés, finalista de la Champions League en 2019.", "Tottenham"],
    ["Alero, campeón de la NBA en 2024 con los Boston Celtics.", "Tatum"]
  ],
  "U": [
    ["Banda irlandesa liderada por Bono, con 22 premios Grammy.", "U2"],
    ["Nombre de pila del atleta jamaicano poseedor del récord mundial de 100 metros.", "Usain"],
    ["Nombre de pila de la actriz protagonista de 'Pulp Fiction' y 'Kill Bill'.", "Uma"]
  ],
  "V": [
    ["Nombre de pila del piloto de motociclismo con nueve títulos mundiales.", "Valentino"],
    ["Piloto alemán de F1, cuatro campeonatos consecutivos con Red Bull.", "Vettel"],
    ["Futbolista colombiano, icónico por su peinado afro en los años noventa.", "Valderrama"],
    ["Delantero español, máximo goleador histórico de la selección española.", "Villa"],
    ["Cantante estadounidense de R&B, autor de 'Never Too Much'.", "Vandross"],
    ["Actor estadounidense, Óscar por 'El regreso' (1978).", "Voight"],
    ["Novelista francés, autor de 'Veinte mil leguas de viaje submarino'.", "Verne"],
    ["Novelista peruano, Nobel de Literatura en 2010.", "Vargas Llosa"],
    ["Club español, finalista de dos Champions League consecutivas en 2000 y 2001.", "Valencia"],
    ["Tenista estadounidense, hermana mayor de Serena, siete títulos de Grand Slam.", "Venus"]
  ],
  "Y": [
    ["Portero soviético, único guardameta en ganar el Balón de Oro, en 1963.", "Yashin"],
    ["Actriz malasia, Óscar por 'Everything Everywhere All at Once'.", "Yeoh"]
  ]
};
